train_path: /content/data/chest_xray/train
test_path: /content/data/chest_xray/test
save_path: ./save
train_batch: 128
dev_batch: 128
test_batch: 128
num_worker: 2
aug: False
patience: 5
image_C:  3
image_W: 224
image_H: 224
model: vgg16 # resnet50, resnet18, vgg16, vgg19
load_pretrained: True
freeze: False
num_classes: 2
learning_rate: 0.001
num_epochs: 100
best_metric: accuracy